name       : qt5-charts
version    : 5.11.1
release    : 6
source     :
    - https://mirrors.ocf.berkeley.edu/qt/official_releases/qt/5.11/5.11.1/submodules/qtcharts-everywhere-src-5.11.1.tar.xz : 62f65f08b08c1fdce4f358103be1f7d7aba54d21774e1a9bfff91314ad667a2b
license    : GPL-3.0
component  : desktop.qt
summary    : Qt Charts module provides a set of easy to use chart components.
description: |
    Qt Charts module provides a set of easy to use chart components. It uses the Qt Graphics View Framework, therefore charts can be easily integrated to modern user interfaces. Qt Charts can be used as QWidgets, QGraphicsWidget, or QML types. Users can easily create impressive graphs by selecting one of the charts themes.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(gl)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
